[package]
name = "flow"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
chrono = { workspace = true }
tray-icon = { workspace = true }
image = { workspace = true }
winit = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
crossbeam = { workspace = true }
app_controller = { workspace = true }
idler_utils = { workspace = true }
mitigations = { workspace = true }

[build-dependencies]
tauri-winres = { workspace = true }

[package.metadata.tauri-winres]
LegalCopyright = "IF©2025"
OriginalFilename = "flow.exe"

[package.metadata.cargo-machete]
ignored = ["tauri-winres"]

[lints]
workspace = true
