[package]
name = "flow"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[package.metadata.tauri-winres]
LegalCopyright = "IF©2025"
OriginalFilename = "flow.exe"

[package.metadata.cargo-machete]
ignored = ["tauri-winres"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []

[dependencies]
app_controller = { workspace = true }
chrono = { workspace = true }
crossbeam = { workspace = true }
idler_utils = { workspace = true }
image = { workspace = true }
mitigations = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tray-icon = { workspace = true }
winit = { workspace = true }

[build-dependencies]
rand = { workspace = true }
tauri-winres = { workspace = true }

[lints]
workspace = true
