[package]
name = "idler_utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
mitigations = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
crossbeam = { workspace = true }
rand = { workspace = true }
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_System_Power",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_System_SystemInformation",
] }


[lints]
workspace = true
